//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCardWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedCard
    {
        public int Id { get; set; }
        public Nullable<int> UsersId { get; set; }
        public string title { get; set; }
        public string discription { get; set; }
    
        public virtual User User { get; set; }
    }
}
